Update aquasec.yaml

diff --git a/.github/workflows/aquasec.yaml b/.github/workflows/aquasec.yaml
--- a/.github/workflows/aquasec.yaml
+++ b/.github/workflows/aquasec.yaml
@@ -23,6 +23,15 @@ jobs:
     runs-on: ubuntu-latest
     environment: main
     steps:
+      - name: Setup Pipeline Enforcer
+        uses: aquasecurity/pipeline-enforcer-action@main
+        env:
+          CSPM_URL: https://asia-1.api.cloudsploit.com
+          AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
+        with:
+          aqua-key: ${{ secrets.AQUA_KEY }}
+          aqua-secret: ${{ secrets.AQUA_SECRET }}
+          
       - name: Checkout code
         uses: actions/checkout@v4
         
@@ -42,6 +51,24 @@ jobs:
           CSPM_URL: https://asia-1.api.cloudsploit.com
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)
+          
+      - name: Manifest Generation (SBOM)
+        run: |
+          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url https://asia-1.api.cloudsploit.com \
+            --artifact-path "$GITHUB_WORKSPACE"
 
   image-scanning:
     name: Aqua Image Scanner
@@ -49,6 +76,15 @@ jobs:
     runs-on: ubuntu-latest
     environment: main
     steps:
+      - name: Setup Pipeline Enforcer
+        uses: aquasecurity/pipeline-enforcer-action@main
+        env:
+          CSPM_URL: https://asia-1.api.cloudsploit.com
+          AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
+        with:
+          aqua-key: ${{ secrets.AQUA_KEY }}
+          aqua-secret: ${{ secrets.AQUA_SECRET }}
+          
       - name: Checkout code
         uses: actions/checkout@v4
         
