Update aquasec.yaml

diff --git a/.github/workflows/aquasec.yaml b/.github/workflows/aquasec.yaml
--- a/.github/workflows/aquasec.yaml
+++ b/.github/workflows/aquasec.yaml
@@ -4,41 +4,72 @@ on:
     branches:
       - main
 jobs:
-  checkout:
-    name: Checkout
-    runs-on: ubuntu-18.04
+  all-in-one:
+    name: Aqua scanner
+    runs-on: ubuntu-latest
+    environment: main
+    env:
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      DOCKER_REGISTRY: "stanhoe"
+      DOCKER_REPOSITORY: "graphql"
+      IMAGE_TAG: ${{ github.sha }}
+      AQUA_KEY: ${{ secrets.AQUA_KEY }}
+      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+      TRIVY_RUN_AS_PLUGIN: 'aqua'
+      GITHUB_TOKEN: ${{ github.token }}
+      AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
+      CSPM_URL: https://asia-1.api.cloudsploit.com
+      BUILD_NUMBER: ${{ github.run_id }}
+      BUILD_NAME: ${{ github.repository }}
+      AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
+      AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
+      AQUA_USER: ${{ secrets.AQUA_USER }} # Aqua Registry
+      AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry
+      
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Login to DockerHub
-        uses: docker/login-action@v2
+        uses: actions/checkout@v4
+        
+      - name: Run Aqua Code Scanner
+        uses: docker://aquasec/aqua-scanner
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Run Trivy vulnerability scanner - FS mode
-        uses: aquasecurity/trivy-action@master
-        with:
-          scan-type: 'fs'
-          security-checks: 'vuln,config,secret'
-          hide-progress: false
-          format: 'table'
-        env:
-          AQUA_KEY: ${{ secrets.AQUA_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          TRIVY_RUN_AS_PLUGIN: 'aqua'
-          TRIGGERED_BY: 'PUSH'
-          GITHUB_TOKEN: ${{ github.token }}
-      - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          push: true
-          tags: "xephil/graphql-vuln:${{ github.sha }}"
+          args: trivy -d fs --scanners config,vuln,secret . --sast --reachability
+          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
+          # To enable SAST scanning, add: --sast
+          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj  
+          
+      - name: Build image locally
+        run: |
+          docker build -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" .
+          
+      - name: Run Aqua Image Scanner
+        run: |
+          docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
+          docker pull registry.aquasec.com/scanner:2404.30.6 
+          docker run --rm -v $GITHUB_WORKSPACE:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e BUILD_NUMBER=$BUILD_NUMBER -e BUILD_JOB_NAME=$BUILD_NAME registry.aquasec.com/scanner:2404.30.6 scan -w /tmp --host $AQUA_HOST --token $AQUA_TOKEN --show-negligible --local $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG --register-compliant --registry "Docker Hub" --htmlfile /tmp/out.html --jsonfile /tmp/out.json > /dev/null
+          
       - name: Manifest Generation
         run: |
-          docker image ls
-          curl -L https://prod-aqua-billy.codesec.aquasec.com/v1/api/download/sh | sh
-          billy generate \
-              --access-token "${{ secrets.GITHUB_TOKEN }}" \
-             --aqua-key "${{ secrets.AQUA_KEY }}" \
-             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-             --artifact-path "xephil/graphql-vuln:${{ github.sha }}"
+          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url https://asia-1.api.cloudsploit.com \
+            --artifact-path "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
+            
+      - name: Tag and push image to Docker Hub (+latest)
+        run: |
+          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
+          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
+          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
